# Generated by Django 3.2 on 2022-02-21 00:56

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter', '0001_install_citext_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('twitter_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Twitter ID')),
                ('username', django.contrib.postgres.fields.citext.CICharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Username')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Target User',
                'verbose_name_plural': 'Target Users',
            },
        ),
    ]
