# Generated by Django 3.2 on 2022-03-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_targetuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetuser',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Twitter ID'),
        ),
    ]
